# Theme
osc=no
border=no

# Video settings
vo=gpu-next
hwdec=auto

# Audio settings
audio-file-auto=fuzzy
alang=eng,en
audio-channels=stereo
ad-lavc-downmix=yes

# Subtitle settings
sub-auto=fuzzy
slang=eng,en
; sub-visibility=no
thumbnails=all

# Profiles
[Idle]
profile-cond=p["idle-active"]
profile-restore=copy-equal
title=''
keepaspect=no
ytdl-raw-options=remote-components=ejs:github
